### ISSUE TITLE
Issue while doing training

### ISSUE THREAD

**Issue by rohaantahir** [jac99/FootAndBall#6]
Thanks @jac99  for wonderfull work. I was trying to do training on your required dataset but getting the following error:

Training...
  0%|                                                                                        | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/fastscenario/football/Football_detect/train_detector.py", line 155, in <module>
    train(params)
  File "/home/fastscenario/football/Football_detect/train_detector.py", line 139, in train
    train_model(model, optimizer, scheduler, params.epochs, dataloaders, device, model_name)
  File "/home/fastscenario/football/Football_detect/train_detector.py", line 66, in train_model
    for ndx, (images, boxes, labels) in enumerate(dataloaders[phase]):
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 308, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/fastscenario/football/Football_detect/data/spd_bmvc2017_dataset.py", line 59, in __getitem__
    image, boxes, labels = self.transform((image, boxes, labels))
  File "/home/fastscenario/football/Football_detect/data/augmentation.py", line 320, in __call__
    return self.augment(sample)
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/fastscenario/football/Football_detect/data/augmentation.py", line 225, in __call__
    coeffs = F._get_inverse_affine_matrix(center, angle, translate, scale, shear)
  File "/home/fastscenario/anaconda3/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 921, in _get_inverse_affine_matrix
    sx, sy = [math.radians(s) for s in shear]
TypeError: 'float' object is not iterable

Can you please tell me what the error is? I think there may be some library misconfiguration. If you could suggest to me something it would be nice of you.
Thanks

**Comment by jac99** [comment]
This is fixed now.
